import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import {headers} from "next/headers";
import {config} from "src/config";
import {cookieToInitialState} from "wagmi";
import AppKitProvider from "src/context";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <AppKitProvider initialState={initialState}>
                  {children}
          </AppKitProvider>
      </body>
    </html>
  );
}
