CREATE DATABASE IF NOT EXISTS `freebe-local`;

USE `freebe-local`;

CREATE TABLE IF NOT EXISTS `node` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `x` FLOAT NOT NULL DEFAULT 0,
    `y` FLOAT NOT NULL DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE INDEX `idx_coordinates` ON `node` (`x`, `y`);

INSERT INTO `node` (`x`, `y`) VALUES (0, 0);
